// Pre-defined list of global financial leaders
export const LEADERS = [
  "Donald Trump",
  "Elon Musk",
  "Warren Buffett",
  "Janet Yellen",
  "Jerome Powell",
  "Christine Lagarde",
  "Larry Fink",
  "Jamie Dimon",
  "Ray Dalio",
  "Cathie Wood",
  "Mark Zuckerberg",
  "Tim Cook",
  "Satya Nadella",
  "Sundar Pichai",
  "Jeff Bezos",
  "Bill Gates",
  "George Soros",
  "Michael Bloomberg",
  "Mario Draghi",
  "Narendra Modi",
];
